mapvote.title=Vote for the next map! (%ds left)
mapvote.rtv_requested=%s has voted to Rock the Vote. (%d/%d)
mapvote.rtv_wait=You must wait a bit before voting!
mapvote.rtv_vote_in_progress=There is currently a vote in progress!
mapvote.rtv_voted=You have already voted to Rock the Vote!
mapvote.rtv_map_changing=There has already been a vote, the map is going to change!
mapvote.rtv_not_enough_players=You need more players before you can rock the vote!
mapvote.rtv_success_delayed=The vote has been rocked, map vote will begin on round end
mapvote.rtv_success_now=The vote has been rocked, map vote imminent
mapvote.nomination_requested=%s has nominated %s.
mapvote.nomination_change=%s has changed their nomination to %s.
mapvote.nomination_not_in_mapcycle=The map you selected is not in the mapcycle.
mapvote.nomination_recent=The map you chose was recently played and cannot be nominated.
mapvote.nomination_cant_nominate_current_map=The map you chose is the current map and cannot be nominated.
mapvote.nomination_max_reached=The maximum allowed nominations has been reached.
mapvote.nomination_menu_title=Select a map
mapvote.nomination_recently_played=Recently Played
mapvote.nomination_nominated=Nominated
mapvote.nomination_current_map=Current Map
