mapvote.seconds=seconds
mapvote.rtv_requested=%s has voted to Rock the Vote. (%d/%d)
mapvote.rtv_wait=You must wait a bit before voting!
mapvote.rtv_vote_in_progress=There is currently a vote in progress!
mapvote.rtv_voted=You have already voted to Rock the Vote!
mapvote.rtv_map_changing=There has already been a vote, the map is going to change!
mapvote.rtv_not_enough_players=You need more players before you can rock the vote!
mapvote.rtv_success_delayed=The vote has been rocked, map vote will begin on round end
mapvote.rtv_success_now=The vote has been rocked, map vote imminent
